<?php

declare(strict_types=1);

namespace Vaqtyar\Tools\Rename;

/**
 * Replaces one technical identity with another across the plugin's files
 * (ADR-000). plan() reads and validates everything, including that no old
 * token would be left; apply() only writes what plan() produced.
 */
final class Renamer
{
    /**
     * Never rewritten nor checked: the docs and the agent instructions keep the
     * working name as history, and lock files are regenerated by their tools
     * (their integrity hashes would otherwise match short tokens by chance).
     */
    private const EXCLUDED_PREFIXES = ['docs/', '.claude/', 'vendor/', 'node_modules/', 'build/', 'dist/'];
    private const EXCLUDED_FILES = [
        'CLAUDE.md',
        'skills-lock.json',
        'composer.lock',
        'pnpm-lock.yaml',
        'package-lock.json',
        'yarn.lock',
    ];

    private const IDENTITY_JSON = 'identity.json';
    private const IDENTITY_CLASS = 'src/Kernel/Identity.php';

    /** How many leftovers an error message lists. */
    private const REPORT_LIMIT = 20;

    /** @var list<string> */
    private readonly array $files;

    /**
     * @param list<string> $files Paths relative to $root, e.g. from `git ls-files`.
     */
    public function __construct(private readonly string $root, array $files)
    {
        $this->files = \array_values(\array_filter(
            \array_map(static fn (string $path): string => \str_replace('\\', '/', $path), $files),
            fn (string $path): bool => !self::isExcluded($path) && \is_file($this->root . '/' . $path)
        ));
    }

    public function plan(RenameSpec $from, RenameSpec $to): RenamePlan
    {
        $this->assertTokensAreSafe($from, $to);

        $map = $from->tokenMap($to);
        $contents = [];
        $writes = [];
        $moves = [];
        foreach ($this->files as $path) {
            $content = $this->read($path);
            if (null !== $content) {
                $contents[$path] = $content;
                $renamed = self::replaceTokens($content, $map);
                if ($renamed !== $content) {
                    $writes[$path] = $renamed;
                }
            }
            $newPath = self::replaceTokens($path, $map);
            if ($newPath !== $path) {
                if (\file_exists($this->root . '/' . $newPath) || \in_array($newPath, $moves, true)) {
                    throw new RenameException(\sprintf('Cannot move %s: %s already exists.', $path, $newPath));
                }
                $moves[$path] = $newPath;
            }
        }

        // The name is replaced only where it is known to be, never as a free token.
        $writes[self::IDENTITY_JSON] = self::encodeIdentity($to);
        $writes[self::IDENTITY_CLASS] = self::replaceOnce(
            self::IDENTITY_CLASS,
            $writes[self::IDENTITY_CLASS] ?? $this->readText(self::IDENTITY_CLASS),
            '/(public const NAME = \')[^\']*(\';)/',
            $to->name
        );
        $mainFile = $from->slug . '.php';
        $writes[$mainFile] = self::replaceOnce(
            $mainFile,
            $writes[$mainFile] ?? $this->readText($mainFile),
            '/^( \* Plugin Name:[ \t]+)[^\n]*()$/m',
            $to->name
        );

        // Refuse before anything is written, rather than leave a half-renamed tree.
        $planned = [];
        foreach ($contents as $path => $content) {
            $planned[$moves[$path] ?? $path] = $writes[$path] ?? $content;
        }
        foreach ($moves as $newPath) {
            $planned[$newPath] ??= '';
        }
        $leftovers = self::scan($planned, self::removedTokens($from, $to));
        if ([] !== $leftovers) {
            throw new RenameException(
                "These old tokens would remain (rename them in the code, or pass --name):\n  "
                . \implode("\n  ", \array_slice($leftovers, 0, self::REPORT_LIMIT))
            );
        }

        return new RenamePlan($writes, $moves);
    }

    public function apply(RenamePlan $plan): void
    {
        foreach ($plan->writes as $path => $content) {
            if (false === \file_put_contents($this->root . '/' . $path, $content)) {
                throw new RenameException('Cannot write ' . $path . '.');
            }
        }
        foreach ($plan->moves as $path => $newPath) {
            $target = $this->root . '/' . $newPath;
            if (!\is_dir(\dirname($target)) && !\mkdir(\dirname($target), 0777, true)) {
                throw new RenameException('Cannot create the directory for ' . $newPath . '.');
            }
            if (!\rename($this->root . '/' . $path, $target)) {
                throw new RenameException(\sprintf('Cannot move %s to %s.', $path, $newPath));
            }
            $this->removeEmptyParents($path);
        }
    }

    /**
     * Every line that still contains a removed token, in any letter case, after apply().
     *
     * @param list<string> $files The files as they are now, e.g. from `git ls-files` again.
     * @return list<string> "path:line: token"
     */
    public function leftovers(RenameSpec $from, RenameSpec $to, array $files): array
    {
        $contents = [];
        foreach ((new self($this->root, $files))->files as $path) {
            $contents[$path] = $this->read($path) ?? '';
        }

        return self::scan($contents, self::removedTokens($from, $to));
    }

    private function assertTokensAreSafe(RenameSpec $from, RenameSpec $to): void
    {
        if ($from->identity() === $to->identity()) {
            throw new RenameException('The new identity is the same as the current one.');
        }

        $old = $from->searchTokens();
        $new = \array_values(\array_diff($to->searchTokens(), $old));
        foreach ($new as $token) {
            foreach ($old as $oldToken) {
                if (\str_contains($token, $oldToken)) {
                    throw new RenameException(\sprintf('"%s" contains the old token "%s".', $token, $oldToken));
                }
            }
        }

        // A new token already used for something else could not be told apart
        // from ours by a later rename. Old tokens are blanked out first, and the
        // old name only where it is replaced.
        $nameFiles = [self::IDENTITY_JSON, self::IDENTITY_CLASS, $from->slug . '.php'];
        foreach ($this->files as $path) {
            $content = $this->read($path);
            if (null === $content) {
                continue;
            }
            $blanked = \str_ireplace(
                \in_array($path, $nameFiles, true) ? [$from->name, ...$old] : $old,
                "\0",
                $content
            );
            foreach ($new as $token) {
                if (false !== \stripos($blanked, $token)) {
                    throw new RenameException(\sprintf('"%s" already appears in %s; choose another.', $token, $path));
                }
            }
        }
    }

    /**
     * Replaces whole tokens only: not when a letter or digit touches them, so
     * a short prefix never rewrites part of an unrelated word or hash.
     *
     * @param array<string, string> $map
     */
    private static function replaceTokens(string $text, array $map): string
    {
        $tokens = \array_keys($map);
        \usort($tokens, static fn (string $a, string $b): int => \strlen($b) <=> \strlen($a));
        $pattern = '/(?<![A-Za-z0-9])('
            . \implode('|', \array_map(static fn (string $t): string => \preg_quote($t, '/'), $tokens))
            . ')(?![A-Za-z0-9])/';

        return (string) \preg_replace_callback($pattern, static fn (array $m): string => $map[$m[1]], $text);
    }

    /**
     * @param array<string, string> $contents Keyed by path.
     * @param list<string> $tokens
     * @return list<string> "path:line: token"
     */
    private static function scan(array $contents, array $tokens): array
    {
        $found = [];
        foreach ($contents as $path => $content) {
            foreach ($tokens as $token) {
                if (false !== \stripos($path, $token)) {
                    $found[] = \sprintf('%s (path): %s', $path, $token);
                }
            }
            foreach (\explode("\n", $content) as $index => $line) {
                foreach ($tokens as $token) {
                    if (false !== \stripos($line, $token)) {
                        $found[] = \sprintf('%s:%d: %s', $path, $index + 1, $token);
                    }
                }
            }
        }

        return $found;
    }

    /**
     * Tokens of $from that $to does not keep (e.g. none but the name changed).
     *
     * @return list<string>
     */
    private static function removedTokens(RenameSpec $from, RenameSpec $to): array
    {
        return \array_values(\array_diff($from->searchTokens(), $to->searchTokens()));
    }

    /**
     * Puts $value between the pattern's two groups. The value is inserted
     * verbatim, never read as a replacement string ("$1" in a name stays "$1").
     */
    private static function replaceOnce(string $path, string $content, string $pattern, string $value): string
    {
        $result = \preg_replace_callback(
            $pattern,
            static fn (array $m): string => $m[1] . $value . $m[2],
            $content,
            -1,
            $count
        );
        if (1 !== $count || !\is_string($result)) {
            throw new RenameException(
                \sprintf('%s: expected exactly one match for %s, found %d.', $path, $pattern, $count)
            );
        }

        return $result;
    }

    private static function encodeIdentity(RenameSpec $spec): string
    {
        $flags = \JSON_PRETTY_PRINT | \JSON_UNESCAPED_SLASHES | \JSON_UNESCAPED_UNICODE | \JSON_THROW_ON_ERROR;
        $json = \json_encode($spec->identity(), $flags);

        // Tabs, as .editorconfig asks for JSON other than composer.json.
        return \preg_replace_callback(
            '/^(?: {4})+/m',
            static fn (array $m): string => \str_repeat("\t", \intdiv(\strlen($m[0]), 4)),
            $json
        ) . "\n";
    }

    /**
     * @return string|null Null for binary files, which are never changed.
     */
    private function read(string $path): ?string
    {
        $content = \file_get_contents($this->root . '/' . $path);
        if (false === $content) {
            throw new RenameException('Cannot read ' . $path . '.');
        }

        return \str_contains($content, "\0") ? null : $content;
    }

    private function readText(string $path): string
    {
        if (!\is_file($this->root . '/' . $path)) {
            throw new RenameException($path . ' does not exist.');
        }

        return $this->read($path) ?? throw new RenameException($path . ' is not a text file.');
    }

    private function removeEmptyParents(string $path): void
    {
        $dir = \dirname($path);
        while ('.' !== $dir && \is_dir($this->root . '/' . $dir)) {
            if ([] !== \array_diff((array) \scandir($this->root . '/' . $dir), ['.', '..'])) {
                return;
            }
            \rmdir($this->root . '/' . $dir);
            $dir = \dirname($dir);
        }
    }

    private static function isExcluded(string $path): bool
    {
        if (\in_array($path, self::EXCLUDED_FILES, true)) {
            return true;
        }
        foreach (self::EXCLUDED_PREFIXES as $prefix) {
            if (\str_starts_with($path, $prefix)) {
                return true;
            }
        }

        return false;
    }
}
